# Generated by Django 4.2.3 on 2023-07-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_remove_userprofileinfo_admin_field_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='admin_approve',
            new_name='admin_approved',
        ),
    ]
