# Generated by Django 4.2.3 on 2023-07-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_app', '0004_rename_admin_approve_userprofileinfo_admin_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('course_image_url', models.ImageField(blank=True, upload_to='course_image_url')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Math 1', 'Math 1'), ('Math 2', 'Math 2'), ('Math 3', 'Math 3'), ('Math 4', 'Math 4'), ('Math 5', 'Math 5'), ('Math 6', 'Math 6'), ('Math 7', 'Math 7'), ('Math 8', 'Math 8'), ('Math 9', 'Math 9'), ('Math 10', 'Math 10'), ('Math 11', 'Math 11'), ('Math 12', 'Math 12')])),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
