# Generated by Django 4.2.3 on 2023-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0006_alter_addcourse_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
