# Generated by Django 4.2.3 on 2023-07-18 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_app', '0007_alter_addcourse_course_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCourse',
            new_name='CreateCourse',
        ),
    ]
