# Generated by Django 4.2.3 on 2023-07-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0012_editcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditComment',
        ),
    ]
