# Generated by Django 4.2.3 on 2023-07-23 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0020_alter_comments_user_comments_alter_createcourse_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_comments',
            field=models.TextField(max_length=250, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
