# Generated by Django 4.2.3 on 2023-07-24 11:12

import datetime
from django.db import migrations, models
import teacher_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0021_alter_comments_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcourse',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 24)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics', validators=[teacher_app.validators.validate_profile_pic]),
        ),
    ]
