# Generated by Django 4.2.3 on 2023-07-24 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0022_alter_createcourse_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcourse',
            name='description',
            field=models.TextField(max_length=800, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='description',
            field=models.TextField(max_length=800, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
