# Generated by Django 4.2.3 on 2023-07-24 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0023_alter_createcourse_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default=1, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default=1, validators=[django.core.validators.MinLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
