# Generated by Django 4.2.3 on 2023-07-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0024_userprofileinfo_first_name_userprofileinfo_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
    ]
