# Generated by Django 4.2.3 on 2023-07-26 10:05

import datetime
from django.db import migrations, models
import teacher_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0027_alter_createcourse_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcourse',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
        migrations.AlterField(
            model_name='searchmodel',
            name='search_text',
            field=models.CharField(max_length=255, validators=[teacher_app.validators.search_validator]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, validators=[teacher_app.validators.description_validator]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='file',
            field=models.FileField(blank=True, upload_to='user_files'),
        ),
    ]
